### ISSUE TITLE
Glow not glowing

### ISSUE THREAD

**Issue by Hexport** [MrHDR/Player_Glow_Sponge#1]
Hey there, thanks for the great plugin!

I recently installed this on my server (Running Sky Factory 3.08, SpongeForge 5.2.0, Minecraft 1.10.2)
and it worked great for a night. Came back on this morning and tried to toggle the glow, but nothing happens now. No glow, no messages, nothing glow related in the logs or console.

I noticed Sponge API is a requirement, does SpongeForge count or should I install the actual API on top? Other than that, not sure what I'm doing wrong, but would appreciate any assistance you might provide. Thanks in advance o7

**Comment by Hexport** [comment]
Went back online and tried to toggle again, noticed an Effect timer indicating Glow, put on a helmet and my glow reappeared. Guess that is a pretty easy workaround. 

Oh and "Dark Purple" looks like a dim "Light Purple", which is, in fact, actually Pink. So "Dark Purple" is really dark pink. As a huge fan of many things Purple I cannot help but point this out. *grumble grumble* :)

Let me know if there is any information I can provide that might ease your diagnosis and resolution of this issue (not the me bitching about the color purple part).

**Comment by Hexport** [comment]
I think it has something to do with the [Holograms](https://ore.spongepowered.org/RandomByte/Holograms) plugin.

The problem is back and I've noticed that toggling Glow seems to turn off/on portions of (possibly just nearby) holograms. Toggling back and forth seems to restore the holograms so far. 

Sadly, my Glow won't come back on. I am unglowed.

**Comment by HDR** [comment]
1: This works on both SpongeVanilla and SpongeForge
2: The color names are their default names in Minecraft
3: i have now knowledge how holograms work i can't really be much help there

As for the effect not appearing, if you're wearing a Draconic helmet it will clear potion effects.

if you have any more questions feel free to ask :)
