### ISSUE TITLE
Only White Glow

### ISSUE THREAD

**Issue by Yorkforce** [MrHDR/Player_Glow_Sponge#10]
On version 1.3.0
Spongeforge 3666

The colours dont seem to be getting applied, only white

![WhiteGlow](https://user-images.githubusercontent.com/1526195/56549060-abd7b700-6579-11e9-909b-4bdf1444f6be.png)

**Comment by HDR** [comment]
Do you have any scoreboard plugins installed?

**Comment by Yorkforce** [comment]
No, nothing related to scoreboards at all as far as I am aware.

Unless a mod is using it in some way, this is on a Sky Factory 4 modpack server.

**Comment by HDR** [comment]
Make sure your permissions are correct

**Comment by Yorkforce** [comment]
The permissions are correct
It wouldn't say Red Glow enabled or allow me to click the menu if there was an issue there.

Even the colorData.json file has my UUID with 'Red' after it

**Comment by Yorkforce** [comment]
It was BungeeTabListPlus @MrHDR Its all working great now :)
