### ISSUE TITLE
Color Change not working

### ISSUE THREAD

**Issue by MageFX** [MrHDR/Player_Glow_Sponge#2]
I can toggle glow on and off
I use GUI and Chat commands but the colors stay white.

SpongeForge 2341.

**Comment by MageFX** [comment]
The Conflict is with EasyScoreboard. Sorry just had time to remove plugins to work it out.

**Comment by HDR** [comment]
This is probably because we both call our scoreboards "scoreboard" i'll look into changing/testing this in the next update.

**Comment by HDR** [comment]
Please try using the jar in this zip file instead.
**Removed**

**Comment by MageFX** [comment]
Unfortunately this does not fix the issue.

**Comment by HDR** [comment]
I'll have to take some time to look into this issue at later date, no guaratee of a fix however.

**Comment by MageFX** [comment]
I'll get my dev to look into it if you like also

**Comment by HDR** [comment]
Sure, can't hurt to have another set of eyes look at it.
