### ISSUE TITLE
Not working with recent spongeforge update

### ISSUE THREAD

**Issue by Yorkforce** [MrHDR/Player_Glow_Sponge#7]
Noticed in the logs we started seeing this error after updating to the latest spongeforge 2747

https://pastebin.com/14RYnH8H

Ingame there is still a white glow but no /glow command (unknown command)

**Comment by HDR** [comment]
Could you try renaming colorData.json (plugins/config/playerglow/) to something else and restarting your server? it looks like your .json file is empty, it should have two brackets in it.

**Comment by HDR** [comment]
Just pushed a new version that should fix this issue when the server starts, please let me know if you still experience this issue afterwards.

**Comment by Yorkforce** [comment]
Yep you were right, I know what's happened now.

Earlier in the week we had a server that generated a huge forge log file (100GB+) and filled our SSD completely causing some servers to crash, some plugins subsequently were unable to reload files and wiped the data as a result, the rename/restart seems to have generated a proper colorData.json.

Sorry about that.

**Comment by HDR** [comment]
No worries, i've also added some code to prevent this in the future.
