### ISSUE TITLE
Adding no-collision to scoreboard

### ISSUE THREAD

**Issue by SnowBlitzz** [MrHDR/Player_Glow_Sponge#8]
Hello,

Since this plugin does not work well together with other plugins that use a scoreboard, I was wondering if it's possible to have a few config settings for its own scoreboard system, such as the no-collision tag.

**Comment by HDR** [comment]
I don't see why not, i'll see if i got some time to look into this next weekend :)

**Comment by SnowBlitzz** [comment]
Thanks! This would really be helpful

**Comment by HDR** [comment]
https://github.com/MrHDR/Player_Glow_Sponge/commit/187c815f5869b4e519fe539237cf57dbd618b3e7

**Comment by HDR** [comment]
This was just thrown together fairly quickly, but as it stands it should work.
